{% set name = "xlsx2html" %}
{% set version = "0.6.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://files.pythonhosted.org/packages/c6/1b/770c7c3d73b7dd0309f8aa640be19782f6762f03caa871edcb8c3fbd0ae6/xlsx2html-0.6.2.tar.gz"
  sha256: e3be926dca7c3217eabe6b9e4e50447b1c65cd2a16a711e395f5e9a1ac18ce9e

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch:
    python

requirements:
  host:
    - babel >=2.3.4
    - openpyxl >=2.4.8
    - packaging >=20.4
    - pip
    - python
    - six
  run:
    - babel >=2.3.4
    - openpyxl >=2.4.8
    - packaging >=20.4
    - python
    - six

test:
  imports:
    - xlsx2html
    - xlsx2html.constants
    - xlsx2html.format
    - xlsx2html.utils

about:
  home: "https://github.com/Apkawa/xlsx2html"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "An XLSX to HTML convertor"
  doc_url: 
  dev_url: https://github.com/Apkawa/xlsx2html

extra:
  recipe-maintainers:
    - https://github.com/gb119
