
name: Conda

on:
  push

# workflow_dispatch:        # Un comment line if you also want to trigger action manually

jobs:
  conda_deployment_with_new_tag:
    name: Conda deployment of package for platform ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@505e6394dae86d6a5c7fbb6e3fb8938e3e863830
        with:
          python-version: "3.12"
          environment-file: env.yaml
          activate-environment: build
          auto-update-conda: true
          auto-activate-base: false
          show-channel-urls: true
      - name: Build and upload the conda packages
        uses: uibcdf/action-build-and-upload-conda-packages@4940704d2be7906d3bda5b00e3c3e4472fd7808f
        with:
          meta_yaml_dir: .
          overwrite: true
          python-version: "3.12"
          user: phygbu
          label: main
          token: ${{ secrets.ANACONDA }} # Replace with the right name of your secret
